Added new shortcuts
ElliottLMz/devforumplus pull request #19
Opened 2020-11-30 06:53 UTC by zapacni

Active forum users may find that they are often flagging duplicates, for instance in Scripting Support, "how do i script" is asked daily. !!DUPE is to tell a user yourself in a DM that they should search; !!DUPEFLAG is for when you want to flag the user.

2020-11-30 06:54 UTC, zapacni commented
Feel free to suggest alternative wording as well since I felt it could be improved somewhere.

2020-11-30 17:56 UTC, FxllenCode commented
Looks pretty good. (And I'll open a new issue for this,) but you can't use these shortcuts by clicking message from their name. I might be able to fix but I'll see.

2020-11-30 18:01 UTC, zapacni commented
You can, but you just need to clear everything first, since when you click on message from their name in a post, it adds a link to their post at the beginning

2020-11-30 18:02 UTC, FxllenCode commented
Huh. Strange, but your right. Thanks!

2020-12-01 03:45 UTC, posatta requested changes
When you're typing !!DUPEFLAG, it'd autofill for !!DUPE. You might want to change it to !!FLAGDUPE or something.

2020-12-01 03:52 UTC, FxllenCode requested changes
For !!FLAGDUPE, make a new line with /n so it looks cleaner and links to make it easy for DET.

2020-12-01 03:52 UTC, FxllenCode commented on src/templates.js
> +	"!!FLAGDUPE": "Duplicate of: ", // for when you flag; space is for adding search query
Probably should set it so it makes a new line using /n, would look cleaner.

2020-12-01 20:10 UTC, ElliottLMz commented
`!!FLAGDUPE` is harder to write than `Duplicate of:`. I want to keep the number of templates to a relative minimum so I don't feel a need for FLAGDUPE.

2020-12-02 16:00 UTC, ElliottLMz requested changes
!!FLAGDUPE is harder to write than Duplicate of:. I want to keep the number of templates to a relative minimum so I don't feel a need for FLAGDUPE.

2020-12-02 23:36 UTC, zapacni commented
I went ahead and removed !!FLAGDUPE. Thanks

2020-12-03 02:05 UTC, FxllenCode approved these changes
Looks good to me- I'd say it's ready.

2020-12-05 10:53 UTC, ElliottLMz approved these changes

2020-12-05 10:53 UTC, merged